context:
  raw_version: "1.6.1-server-1.31.0-150.0"
  version: "1.6.2-server-1.31.0-151.6"

package:
  name: temporalio-cli
  version: ${{ version }}

source:
  url: https://github.com/temporalio/cli/archive/refs/tags/v${{ raw_version }}.tar.gz
  sha256: ac0bce827d7a051b25e296afd5cd24d580b5772db4888325e478299e3cdc25e5
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save ./cmd/temporal --save_path ../library_licenses --ignore github.com/cactus/go-statsd-client/statsd --ignore modernc.org/mathutil --ignore github.com/apache/thrift/lib/go/thrift --ignore github.com/jmespath/go-jmespath --ignore github.com/temporalio/cli/cliext
    - if: win
      then: go build -ldflags="-s -w -X github.com/temporalio/cli/temporalcli.Version=${{ raw_version }}" -v -o %LIBRARY_BIN%\temporal.exe ./cmd/temporal
      else: go build -ldflags="-s -w -X github.com/temporalio/cli/temporalcli.Version=${{ raw_version }}" -v -o $PREFIX/bin/temporal ./cmd/temporal
    - if: unix
      then:
        - mkdir -p $PREFIX/share/bash-completion/completions
        - temporal completion bash > $PREFIX/share/bash-completion/completions/temporal
        - mkdir -p $PREFIX/share/zsh/site-functions
        - temporal completion zsh > $PREFIX/share/zsh/site-functions/_temporal
        - mkdir -p $PREFIX/share/fish/vendor_completions.d
        - temporal completion fish > $PREFIX/share/fish/vendor_completions.d/temporal.fish

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - temporal --version

about:
  homepage: https://temporal.io/
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
    # these are not properly collected by go-licenses
    - go-statsd-license.txt
    - mathutil-license.txt
    - thrift-license.txt
    - jmespath-license.txt

  summary: Command-line interface for running and interacting with Temporal Server and UI
  description: |
    Temporal CLI is a command-line interface for running and interacting with Temporal Server and UI.
  repository: https://github.com/temporalio/cli
  documentation: https://docs.temporal.io/cli

extra:
  recipe-maintainers:
    - wolfv
